import { NextRequest, NextResponse } from "next/server";
import { Innertube } from "youtubei.js";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 30;

// Extract video ID from YouTube URL
function extractVideoId(url: string): string | null {
  const patterns = [
    /(?:youtube\.com\/watch\?v=|youtu\.be\/)([^&\n?#]+)/,
    /youtube\.com\/embed\/([^&\n?#]+)/,
    /youtube\.com\/v\/([^&\n?#]+)/,
    /youtube\.com\/shorts\/([^&\n?#]+)/,
    /youtube\.com\/live\/([^&\n?#]+)/,
  ];

  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match && match[1]) {
      return match[1];
    }
  }

  if (/^[a-zA-Z0-9_-]{11}$/.test(url)) {
    return url;
  }

  return null;
}

export async function POST(request: NextRequest) {
  console.log("🎬 [YouTube Captions] Request received");

  try {
    const body = await request.json();
    const { url } = body;

    if (!url) {
      return NextResponse.json(
        { error: "YouTube URL is required" },
        { status: 400 }
      );
    }

    const videoId = extractVideoId(url);
    if (!videoId) {
      return NextResponse.json(
        { error: "Invalid YouTube URL" },
        { status: 400 }
      );
    }

    console.log(`🎯 [YouTube Captions] Video ID: ${videoId}`);

    // Create Innertube instance
    const innertube = await Innertube.create({
      lang: "en",
      location: "US",
      retrieve_player: false,
      generate_session_locally: true,
    });

    // Get video info
    const info = await innertube.getInfo(videoId);

    // Get video title from basic info
    const title = info.basic_info?.title || "Unknown";

    // Get captions info
    const captions = info.captions;
    const captionTracks = (captions as any)?.caption_tracks || [];

    // Format caption tracks
    const formattedTracks = captionTracks.map((track: any) => ({
      language: track.language_code || "unknown",
      name: track.name?.text || track.name || "Unknown",
      kind: track.kind || "standard", // "asr" = auto-generated
      isAutoGenerated: track.kind === "asr",
    }));

    console.log(`✅ [YouTube Captions] Found ${formattedTracks.length} caption tracks`);

    return NextResponse.json({
      success: true,
      data: {
        videoId,
        title,
        captionCount: formattedTracks.length,
        captions: formattedTracks,
      },
    });
  } catch (error: any) {
    console.error("❌ [YouTube Captions] Error:", error);
    return NextResponse.json(
      { error: error.message || "Failed to fetch captions" },
      { status: 500 }
    );
  }
}

export async function GET(request: NextRequest) {
  const url = request.nextUrl.searchParams.get("url");

  if (!url) {
    return NextResponse.json(
      { 
        error: "YouTube URL is required",
        usage: "GET /api/youtube/captions?url=YOUTUBE_URL"
      },
      { status: 400 }
    );
  }

  const fakeRequest = new NextRequest(request.url, {
    method: "POST",
    body: JSON.stringify({ url }),
  });

  return POST(fakeRequest);
}
